Zendesk touch
Getaround/stitch-zendesk pull request #42
Opened 2020-01-01 00:22 UTC by arthurgetaround

@fireplacetv

2020-01-02 22:30 UTC, fireplacetv requested changes
Looks good--just requesting a couple small changes.

2020-01-02 22:30 UTC, fireplacetv commented on agent_touch.view.lkml
> +  sql_table_name: dbt_arthur_common.zendesk_ticket_touch ;;
Let's point this to the prod table

2020-01-02 22:30 UTC, fireplacetv commented on agent_touch.view.lkml
> +  }
Will anyone ever need this on its own? I think we can probably leave this hidden.

2020-01-02 22:30 UTC, fireplacetv commented on agent_touch.view.lkml
> +  dimension: ticket_id {
We only need this for the join, so we can leave it hidden. Also, might as well move it up to the top with the other ID.

2020-01-02 22:30 UTC, fireplacetv commented on agent_touch.view.lkml
> +  dimension: agent_email {
Since there are only 4 fields, I actually wouldn't bother grouping these since it just adds extra clicks for the user.

2020-01-02 22:39 UTC, arthurgetaround commented
@fireplacetv Addressed!

2020-01-02 23:04 UTC, fireplacetv approved these changes
lgtm!

2020-01-06 20:38 UTC, jaywmehta approved these changes
LGTM

2020-01-15 21:44 UTC, merged